### ISSUE TITLE
Please update the code of checking thread task's state.

### ISSUE THREAD

**Issue by Barenboim** [MaybeShewill-CV/mortred_model_server#1]
https://github.com/MaybeShewill-CV/mortred_model_server/blob/64b3951a9161a89b98d833df27a5ae330acd2ced/src/server/base_server_impl.h#L316

We are changing a thread/go task's state to WFT_STATE_SYS_ERROR with error ETIMEDOUT when the task was timed out. I am sorry for the change but this will make it possible for users to distinguish between thread task's timeout and program exit. You may update the code to be something like:
~~~cpp
if (state == WFT_STATE_SUCCESS)
{
   // done
}
else
{
   // timeout
}
~~~
to make it compatible with both behaviors.

**Comment by Barenboim** [comment]
https://github.com/MaybeShewill-CV/mortred_model_server/pull/2

**Comment by MaybeShewill-CV** [comment]
@Barenboim Thanks:)
